spring.datasource.url=jdbc:mysql://backend.cxgk82uueb48.ap-south-1.rds.amazonaws.com:3306/backend?useSSL=false&&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=Asrita2002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true